FROM node:v20.14.0

# Create user with permission to run the app
RUN addgroup app && adduser -S -G app app

# Set the user to run the app
USER app

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

USER root

RUN chown -R app:app .

USER app

RUN pnpm install

COPY . .

RUN pnpm run build

# Production stage
FROM nginx/alpine

COPY --from=builder /app/dist /user/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]